- ansible.builtin.import_role:
    name: common_tasks
    tasks_from: build_directory

- ansible.builtin.import_role:
    name: common_tasks
    tasks_from: remote_directory

- ansible.builtin.import_role:
    name: compose_hull
    tasks_from: facts
  vars:
    service_defaults:
      name: worker_local_ubuntu2404_ssh
      traefik: false
      external: false
      watchtower: false
      autoheal: false
      gpus: ["0"]

- name: "Define project home path"
  ansible.builtin.set_fact:
    project_home_path: "/home/{{ service_cfg.user }}/{{ service_cfg.project_name }}"

- ansible.builtin.import_role:
    name: common_tasks
    tasks_from: local_directory

- ansible.builtin.import_role:
    name: common_tasks
    tasks_from: populate_home_with_console_settings

- ansible.builtin.import_role:
    name: compose_hull
    tasks_from: user_info

- ansible.builtin.import_role:
    name: common_tasks
    tasks_from: build_image

- ansible.builtin.import_role:
    name: common_tasks
    tasks_from: ensure_network

- ansible.builtin.import_role:
    name: common_tasks
    tasks_from: start_container