"""Add cpu limits tables

Revision ID: 1d28a03a5c98
Revises: 82c08af95a01
Create Date: 2026-01-09 11:15:53.793587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d28a03a5c98'
down_revision = '82c08af95a01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group_cpu_limit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('compute_server_id', sa.Integer(), nullable=False),
    sa.Column('cpu_limit', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['compute_server_id'], ['compute_server.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'compute_server_id', name='_group_server_cpu_uc')
    )
    with op.batch_alter_table('container_instance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cpu_limit', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('container_instance', schema=None) as batch_op:
        batch_op.drop_column('cpu_limit')

    op.drop_table('group_cpu_limit')
    # ### end Alembic commands ###
