"""Add ttl date

Revision ID: 222cf3d26f4f
Revises: 558b284eba92
Create Date: 2025-09-26 17:42:04.811418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '222cf3d26f4f'
down_revision = '558b284eba92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('container_instance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ttl_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('container_instance', schema=None) as batch_op:
        batch_op.drop_column('ttl_date')

    # ### end Alembic commands ###
