"""Add gpu_count to ComputeServer

Revision ID: 277adb2c116d
Revises: 823b2599257c
Create Date: 2025-06-11 14:29:50.292744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '277adb2c116d'
down_revision = '823b2599257c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('compute_server', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gpu_count', sa.Integer(), server_default='1', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('compute_server', schema=None) as batch_op:
        batch_op.drop_column('gpu_count')

    # ### end Alembic commands ###
