"""Add ssh_port to ComputeServer

Revision ID: 281d604f5314
Revises: ef0e5dacc901
Create Date: 2025-05-30 19:37:33.972912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '281d604f5314'
down_revision = 'ef0e5dacc901'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('compute_server', schema=None) as batch_op:
        # Add the column allowing nulls initially
        op.add_column('compute_server', sa.Column('ssh_port', sa.Integer(), nullable=True))
        # Set default for existing rows
        op.execute("UPDATE compute_server SET ssh_port = 22 WHERE ssh_port IS NULL")
        # Alter to be non-nullable
        op.alter_column('compute_server', 'ssh_port',
                        existing_type=sa.Integer(),
                        nullable=False,
                        server_default='22')  # Add server_default for future direct DB inserts too

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('compute_server', schema=None) as batch_op:
        batch_op.drop_column('ssh_port')

    # ### end Alembic commands ###
