"""Add ldap user cache

Revision ID: 2db45a1e512b
Revises: a36e2d3d3e2a
Create Date: 2025-07-21 14:06:30.857260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2db45a1e512b'
down_revision = 'a36e2d3d3e2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ldap_user_cache',
    sa.Column('uid', sa.String(length=128), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('cached_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('uid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ldap_user_cache')
    # ### end Alembic commands ###
