"""add extravars for temporary data needed during job execution

Revision ID: 397fc21b09c1
Revises: bdcc924ff2a3
Create Date: 2025-08-25 12:49:01.054159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '397fc21b09c1'
down_revision = 'bdcc924ff2a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ansible_job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('extravars', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ansible_job', schema=None) as batch_op:
        batch_op.drop_column('extravars')

    # ### end Alembic commands ###
