"""add email field to LdapUserCache

Revision ID: 4255bc6846ba
Revises: 1d28a03a5c98
Create Date: 2026-03-30 18:20:26.909678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4255bc6846ba'
down_revision = '1d28a03a5c98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ldap_user_cache', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ldap_user_cache', schema=None) as batch_op:
        batch_op.drop_column('email')

    # ### end Alembic commands ###
