"""added the FileOperationJob

Revision ID: 558b284eba92
Revises: e3c303db7a45
Create Date: 2025-09-23 15:51:23.673993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '558b284eba92'
down_revision = 'e3c303db7a45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_operation_job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('operation', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('log', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('file_operation_job', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_file_operation_job_operation'), ['operation'], unique=False)
        batch_op.create_index(batch_op.f('ix_file_operation_job_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file_operation_job', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_file_operation_job_status'))
        batch_op.drop_index(batch_op.f('ix_file_operation_job_operation'))

    op.drop_table('file_operation_job')
    # ### end Alembic commands ###
