"""Remove DockerImage model, use image_name string in ContainerInstance

Revision ID: 5ff1e0809bf3
Revises: 8ed7f0fa1f5a
Create Date: 2025-04-24 16:00:33.417659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ff1e0809bf3'
down_revision = '8ed7f0fa1f5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('container_instance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_name', sa.String(length=128), nullable=False))
        batch_op.drop_constraint('container_instance_docker_image_id_fkey', type_='foreignkey')
        batch_op.drop_column('docker_image_id')
    op.drop_table('docker_image')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('container_instance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('docker_image_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('container_instance_docker_image_id_fkey', 'docker_image', ['docker_image_id'], ['id'])
        batch_op.drop_column('image_name')

    op.create_table('docker_image',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('ansible_role_name', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='docker_image_pkey'),
    sa.UniqueConstraint('name', name='docker_image_name_key')
    )
    # ### end Alembic commands ###
