"""empty message

Revision ID: 65e5ef0ccedc
Revises: 93370da9de7f
Create Date: 2025-06-23 15:39:05.160568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65e5ef0ccedc'
down_revision = '93370da9de7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ansible_job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('server_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'compute_server', ['server_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ansible_job', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('server_id')

    # ### end Alembic commands ###
