"""Jobs get actions and store their playbooks

Revision ID: 7411f93b43ae
Revises: bb8e7bdbb00a
Create Date: 2025-06-25 10:31:12.962978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7411f93b43ae'
down_revision = 'bb8e7bdbb00a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ansible_job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('action', sa.String(length=32), server_default='create', nullable=False))
        batch_op.add_column(sa.Column('playbook', sa.Text(), server_default='', nullable=False))
        batch_op.create_index(batch_op.f('ix_ansible_job_action'), ['action'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ansible_job', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ansible_job_action'))
        batch_op.drop_column('playbook')
        batch_op.drop_column('action')

    # ### end Alembic commands ###
