"""Add network model and link to static addresses

Revision ID: 823b2599257c
Revises: 281d604f5314
Create Date: 2025-06-10 14:40:49.970559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '823b2599257c'
down_revision = '281d604f5314'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    network_table = op.create_table('network',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('base_ip', sa.String(length=45), nullable=False),
    sa.Column('prefix_size', sa.Integer(), nullable=False),
    sa.Column('gateway', sa.String(length=45), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )

    op.bulk_insert(network_table, [
        {'id': 1, 'name': 'Default Migrated Network', 'base_ip': '192.168.178.0',
         'prefix_size': 24, 'gateway': '192.168.178.1'}
    ])
    op.execute("SELECT setval('network_id_seq', (SELECT MAX(id) FROM network));")

    op.add_column('static_address', sa.Column('network_id', sa.Integer(), nullable=True))
    op.execute('UPDATE static_address SET network_id = 1')
    op.alter_column('static_address', 'network_id',
                    existing_type=sa.Integer(),
                    nullable=False)

    op.create_foreign_key('fk_static_address_network_id', 'static_address',
                          'network', ['network_id'], ['id'])

    with op.batch_alter_table('static_address', schema=None) as batch_op:
        batch_op.drop_column('gateway')
        batch_op.drop_column('subnet_prefix_size')

    # ### end Alembic commands ###


def downgrade():
    op.add_column('static_address', sa.Column('subnet_prefix_size', sa.Integer(), autoincrement=False, nullable=True))
    op.add_column('static_address', sa.Column('gateway', sa.String(length=45), autoincrement=False, nullable=True))

    # Step 2: Populate the old columns from the network table data before we drop it.
    # This is a best-effort reversal.
    op.execute(
        'UPDATE static_address sa SET gateway = (SELECT gateway FROM network n WHERE n.id = sa.network_id), subnet_prefix_size = (SELECT prefix_size FROM network n WHERE n.id = sa.network_id)')

    # Step 3: Make old columns non-nullable again.
    op.alter_column('static_address', 'gateway', existing_type=sa.String(length=45), nullable=False)
    op.alter_column('static_address', 'subnet_prefix_size', existing_type=sa.Integer(), nullable=False)

    # Step 4: Drop the foreign key constraint and the network_id column.
    op.drop_constraint('fk_static_address_network_id', 'static_address', type_='foreignkey')
    op.drop_column('static_address', 'network_id')

    # Step 5: Drop the network table.
    op.drop_table('network')

    # ### end Alembic commands ###
