"""removed ssh_command field from ContainerInstance

Revision ID: 82c08af95a01
Revises: 222cf3d26f4f
Create Date: 2025-11-17 18:43:28.239538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82c08af95a01'
down_revision = '222cf3d26f4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('container_instance', schema=None) as batch_op:
        batch_op.drop_column('ssh_command')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('container_instance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ssh_command', sa.VARCHAR(length=255), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
