"""Initial database schema

Revision ID: 8ed7f0fa1f5a
Revises: 
Create Date: 2025-04-22 16:14:19.267023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ed7f0fa1f5a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compute_server',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hostname', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('compute_server', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_compute_server_hostname'), ['hostname'], unique=True)

    op.create_table('docker_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('ansible_role_name', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('local_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('local_user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_local_user_username'), ['username'], unique=True)

    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('owner_uid', sa.String(length=128), nullable=True),
    sa.Column('owner_local_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('(owner_uid IS NOT NULL AND owner_local_user_id IS NULL) OR (owner_uid IS NULL AND owner_local_user_id IS NOT NULL)', name='cc_project_owner'),
    sa.ForeignKeyConstraint(['owner_local_user_id'], ['local_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_project_name')
    )
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_project_owner_local_user_id'), ['owner_local_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_owner_uid'), ['owner_uid'], unique=False)

    op.create_table('user_ssh_key',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('local_user_id', sa.Integer(), nullable=True),
    sa.Column('user_uid', sa.String(length=128), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('public_key', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('(user_uid IS NOT NULL AND local_user_id IS NULL) OR (user_uid IS NULL AND local_user_id IS NOT NULL)', name='cc_ssh_key_user'),
    sa.ForeignKeyConstraint(['local_user_id'], ['local_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_uid', 'name', name='_user_ssh_key_uc')
    )
    with op.batch_alter_table('user_ssh_key', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_ssh_key_user_uid'), ['user_uid'], unique=False)

    op.create_table('container_instance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_uid', sa.String(length=128), nullable=True),
    sa.Column('user_local_user_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('compute_server_id', sa.Integer(), nullable=False),
    sa.Column('docker_image_id', sa.Integer(), nullable=False),
    sa.Column('ssh_key_id', sa.Integer(), nullable=True),
    sa.Column('gpus', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('ansible_job_id', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('container_name', sa.String(length=255), nullable=True),
    sa.Column('ssh_command', sa.String(length=255), nullable=True),
    sa.Column('ansible_log', sa.Text(), nullable=True),
    sa.CheckConstraint('(user_uid IS NOT NULL AND user_local_user_id IS NULL) OR (user_uid IS NULL AND user_local_user_id IS NOT NULL)', name='cc_container_user'),
    sa.ForeignKeyConstraint(['compute_server_id'], ['compute_server.id'], ),
    sa.ForeignKeyConstraint(['docker_image_id'], ['docker_image.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['ssh_key_id'], ['user_ssh_key.id'], ),
    sa.ForeignKeyConstraint(['user_local_user_id'], ['local_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('container_instance', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_container_instance_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_container_instance_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_container_instance_user_local_user_id'), ['user_local_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_container_instance_user_uid'), ['user_uid'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('container_instance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_container_instance_user_uid'))
        batch_op.drop_index(batch_op.f('ix_container_instance_user_local_user_id'))
        batch_op.drop_index(batch_op.f('ix_container_instance_status'))
        batch_op.drop_index(batch_op.f('ix_container_instance_created_at'))

    op.drop_table('container_instance')
    with op.batch_alter_table('user_ssh_key', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_ssh_key_user_uid'))

    op.drop_table('user_ssh_key')
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_owner_uid'))
        batch_op.drop_index(batch_op.f('ix_project_owner_local_user_id'))
        batch_op.drop_index(batch_op.f('ix_project_name'))

    op.drop_table('project')
    with op.batch_alter_table('local_user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_local_user_username'))

    op.drop_table('local_user')
    op.drop_table('docker_image')
    with op.batch_alter_table('compute_server', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_compute_server_hostname'))

    op.drop_table('compute_server')
    # ### end Alembic commands ###
