"""empty message

Revision ID: 93370da9de7f
Revises: 9a5477abf4b5
Create Date: 2025-06-23 15:09:05.980986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93370da9de7f'
down_revision = '9a5477abf4b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ansible_job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('container_instance_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('log', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['container_instance_id'], ['container_instance.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ansible_job')
    # ### end Alembic commands ###
