"""Add directory_path to ContainerInstance

Revision ID: 9a5477abf4b5
Revises: 277adb2c116d
Create Date: 2025-06-11 15:17:49.348843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a5477abf4b5'
down_revision = '277adb2c116d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('container_instance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('directory_path', sa.String(length=512), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('container_instance', schema=None) as batch_op:
        batch_op.drop_column('directory_path')

    # ### end Alembic commands ###
