"""empty message

Revision ID: bb8e7bdbb00a
Revises: eaeb023a74b5
Create Date: 2025-06-23 17:24:38.519002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb8e7bdbb00a'
down_revision = 'eaeb023a74b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('container_instance', schema=None) as batch_op:
        batch_op.drop_column('ansible_job_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('container_instance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ansible_job_id', sa.VARCHAR(length=128), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
