"""Make LdapUserCache.cached_at timezone-aware

Revision ID: bdcc924ff2a3
Revises: 2db45a1e512b
Create Date: 2025-07-21 14:39:30.508739

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bdcc924ff2a3'
down_revision = '2db45a1e512b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ldap_user_cache', schema=None) as batch_op:
        batch_op.alter_column('cached_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ldap_user_cache', schema=None) as batch_op:
        batch_op.alter_column('cached_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)

    # ### end Alembic commands ###
