"""add ProjectShare model

Revision ID: e3c303db7a45
Revises: 397fc21b09c1
Create Date: 2025-09-19 18:39:43.526350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3c303db7a45'
down_revision = '397fc21b09c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_share',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('user_uid', sa.String(length=128), nullable=False),
    sa.Column('is_writable', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'user_uid', name='_project_user_uc')
    )
    with op.batch_alter_table('project_share', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_share_user_uid'), ['user_uid'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_share', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_share_user_uid'))

    op.drop_table('project_share')
    # ### end Alembic commands ###
