"""empty message

Revision ID: eaeb023a74b5
Revises: 65e5ef0ccedc
Create Date: 2025-06-23 16:49:21.841232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eaeb023a74b5'
down_revision = '65e5ef0ccedc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('container_instance', schema=None) as batch_op:
        batch_op.drop_column('ansible_log')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('container_instance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ansible_log', sa.TEXT(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
