"""Add static address pool and link to containers/servers

Revision ID: ed4905aa4ac5
Revises: 5ff1e0809bf3
Create Date: 2025-04-29 15:17:42.542763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed4905aa4ac5'
down_revision = '5ff1e0809bf3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('static_address',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('mac_address', sa.String(length=17), nullable=False),
    sa.Column('comment', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('static_address', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_static_address_ip_address'), ['ip_address'], unique=True)
        batch_op.create_index(batch_op.f('ix_static_address_mac_address'), ['mac_address'], unique=True)

    op.create_table('server_static_address_association',
    sa.Column('static_address_id', sa.Integer(), nullable=False),
    sa.Column('compute_server_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['compute_server_id'], ['compute_server.id'], ),
    sa.ForeignKeyConstraint(['static_address_id'], ['static_address.id'], ),
    sa.PrimaryKeyConstraint('static_address_id', 'compute_server_id')
    )
    with op.batch_alter_table('container_instance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('static_address_id', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint(None, ['static_address_id'])
        batch_op.create_foreign_key(None, 'static_address', ['static_address_id'], ['id'])
        batch_op.drop_column('ip_address')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('container_instance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ip_address', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('static_address_id')

    op.drop_table('server_static_address_association')
    with op.batch_alter_table('static_address', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_static_address_mac_address'))
        batch_op.drop_index(batch_op.f('ix_static_address_ip_address'))

    op.drop_table('static_address')
    # ### end Alembic commands ###
