"""Add gateway and subnet prefix size to StaticAddress

Revision ID: ef0e5dacc901
Revises: ed4905aa4ac5
Create Date: 2025-05-05 18:06:41.641539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef0e5dacc901'
down_revision = 'ed4905aa4ac5'
branch_labels = None
depends_on = None


def upgrade():
    # Step 1: Add new columns initially allowing NULLs
    with op.batch_alter_table('static_address', schema=None) as batch_op:
        # Assuming String for gateway, adjust type if using INET
        batch_op.add_column(sa.Column('gateway', sa.String(length=45), nullable=True))
        batch_op.add_column(sa.Column('subnet_prefix_size', sa.Integer(), nullable=True))

    # Step 2: Update existing rows with default values
    # Default Gateway: '192.168.178.1'
    # Default Subnet Size: 24 (for mask 255.255.255.0)
    # Use op.execute() for raw SQL - works well for simple updates
    # This updates only rows where the new columns *are currently NULL*
    op.execute(
        "UPDATE static_address SET gateway = '192.168.178.1', subnet_prefix_size = 24 WHERE gateway IS NULL OR subnet_prefix_size IS NULL")
    # If you prefer to update ALL existing rows regardless of current value (safer if previous attempts failed partially):
    # op.execute("UPDATE static_address SET gateway = '192.168.178.1', subnet_prefix_size = 24")

    # Step 3: Alter columns to enforce NOT NULL constraint
    with op.batch_alter_table('static_address', schema=None) as batch_op:
        batch_op.alter_column('gateway',
                              existing_type=sa.String(length=45),  # Specify existing type
                              nullable=False)
        batch_op.alter_column('subnet_prefix_size',
                              existing_type=sa.Integer(),  # Specify existing type
                              nullable=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('static_address', schema=None) as batch_op:
        batch_op.drop_column('subnet_prefix_size')
        batch_op.drop_column('gateway')

    # ### end Alembic commands ###
