- name: "Ensure /docker exists"
  become: true
  file:
    path: "/docker"
    state: directory
    owner: pina
    group: 1001
    mode: "775"

- name: "Ensure /docker/{{ service_cfg.image_name }}-{{ service_cfg.user }}-{{ service_cfg.project_name }} exists"
  become: true
  file:
    path: "/docker/{{ service_cfg.image_name }}-{{ service_cfg.user }}-{{ service_cfg.project_name }}"
    state: directory
    owner: pina
    group: 1001
    mode: "775"

- name: "Ensure /docker/{{ service_cfg.image_name }}-{{ service_cfg.user }}-{{ service_cfg.project_name }}/build exists"
  become: true
  file:
    path: "/docker/{{ service_cfg.image_name }}-{{ service_cfg.user }}-{{ service_cfg.project_name }}/build"
    state: directory
    owner: pina
    group: 1001
    mode: "775"