- name: "Ensure build directory structure exists"
  file:
    path: "{{ build_path }}/build"
    state: directory
    mode: "0755"

- name: "Copy files for the build"
  ansible.builtin.copy:
    src: '{{ item }}'
    dest: '{{ build_path }}/build/{{ item }}'
  loop:
    - "nopasswd"
    - "entrypoint.sh"

- name: "Prepare Dockerfile"
  ansible.builtin.template:
    src: Dockerfile.j2
    dest: '{{ build_path }}/build/Dockerfile'